language: node_js
addons:
  ssh_known_hosts:
  - quasar.cross-solution.de
node_js:
- '10.15.3'
cache:
  directories:
  - node_modules
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
  - php: '7.2'
branches:
  only:
  - master
before_install:
before_install:
- openssl aes-256-cbc -K $encrypted_e989228ec430_key -iv $encrypted_e989228ec430_iv
  -in .travis/deploy.enc -out ~/.ssh/id_ed25519 -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_ed25519
- ssh-add ~/.ssh/id_ed25519
- curl -LO https://deployer.org/deployer.phar
- chmod +x deployer.phar
install:
- npm install
- npm run generate
script:
- npm run test
deploy:
- provider: script
  skip_cleanup: true
  script: "./deployer.phar deploy"
  on:
    branch: master
